version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    target-branch: "dev"
    commit-message:
      prefix: "chore"