// app
export const SET_COLOR_MODE = 'SET_COLOR_MODE';

// exporter
export const SET_NUMBER_OF_EXPORT_ROWS = 'SET_NUMBER_OF_EXPORT_ROWS';
export const SET_EXPORT_FORMAT = 'SET_EXPORT_FORMAT';
export const SET_FORMATTER_CONFIG = 'SET_FORMATTER_CONFIG';

// workspace
export const SET_PANELS_DIRECTION = 'SET_PANELS_DIRECTION';

// preview
export const SET_PREVIEW_TYPE = 'SET_PREVIEW_TYPE';
export const SET_RAW_VIEW_SHOW_LINE_NUMBERS = 'SET_RAW_VIEW_SHOW_LINE_NUMBERS';
export const SET_RAW_VIEW_LINE_WRAP = 'SET_RAW_VIEW_LINE_WRAP';
export const SET_RAW_VIEW_FONT_SIZE = 'SET_RAW_VIEW_FONT_SIZE';
export const SET_PREVIEW_FORMATTED_DATA = 'SET_PREVIEW_FORMATTED_DATA';