// app
export const SET_LOCALE = 'SET_LOCALE';
export const SET_COLOR_MODE = 'SET_COLOR_MODE';

// exporter
export const SET_NUMBER_OF_EXPORT_ROWS = 'SET_NUMBER_OF_EXPORT_ROWS';
export const SET_EXPORT_FORMAT = 'SET_EXPORT_FORMAT';
export const SET_FORMATTER_CONFIG = 'SET_FORMATTER_CONFIG';

// workspace
export const SET_PANELS_DIRECTION = 'SET_PANELS_DIRECTION';
export const SET_DATA_FIELDS = 'SET_DATA_FIELDS';
export const OPEN_DATA_TYPE_SELECT_MODAL = 'OPEN_DATA_TYPE_SELECT_MODAL';
export const CLOSE_DATA_TYPE_SELECT_MODAL = 'CLOSE_DATA_TYPE_SELECT_MODAL';
export const OPEN_DATA_TYPE_OPTIONS_MODAL = 'OPEN_DATA_TYPE_OPTIONS_MODAL';
export const CLOSE_DATA_TYPE_OPTIONS_MODAL = 'CLOSE_DATA_TYPE_OPTIONS_MODAL';
export const ADD_NEW_DATA_FIELD = 'ADD_NEW_DATA_FIELD';
export const DELETE_DATA_FIELD = 'DELETE_DATA_FIELD';
export const UPDATE_DATA_FIELD = 'UPDATE_DATA_FIELD';
export const SORT_DATA_FIELDS = 'SORT_DATA_FIELDS';
export const CHANGE_DATA_TYPE = 'CHANGE_DATA_TYPE';

// preview
export const SET_PREVIEW_TYPE = 'SET_PREVIEW_TYPE';
export const SET_RAW_VIEW_SHOW_LINE_NUMBERS = 'SET_RAW_VIEW_SHOW_LINE_NUMBERS';
export const SET_RAW_VIEW_LINE_WRAP = 'SET_RAW_VIEW_LINE_WRAP';
export const SET_RAW_VIEW_FONT_SIZE = 'SET_RAW_VIEW_FONT_SIZE';
export const SET_PREVIEW_FORMATTED_DATA = 'SET_PREVIEW_FORMATTED_DATA';