export const en = {

    // -------------------------------------------------------------------------------------------------------------
    // export

    // export category
    "export.category.fileTypes": "General file types",
    "export.category.programmingLanguages": "Programming languages",

    // export format modal
    "export.configurator.modal.title": "Export Format",
    "export.configurator.modal.closeButton.text": "Close",
    "export.configurator.config.label": "Configurations",
    "export.configurator.config.empty": "Configuration of this export format is currently not available.",

    // csv
    "export.configurator.csv.delimiter": "Delimiter",
    "export.configurator.csv.includeHeader": "Include header",
    "export.configurator.csv.endLineChar": "End of line characters",

    // -------------------------------------------------------------------------------------------------------------
    // data types

    // data type category
    "dataType.category.all": "All",
    "dataType.category.basic": "Basic",
    "dataType.category.person": "Person",
    "dataType.category.commerce": "Commerce",

    // number
    "dataType.number": "Number",
    "dataType.number.kind.label": "Kind",
    "dataType.number.precision.label": "Precision",
    "dataType.number.min.label": "Min.",
    "dataType.number.min.tooltip":"Lower bound for generated numbers",
    "dataType.number.min.errorMessage.empty": "Min. value cannot be empty",
    "dataType.number.min.errorMessage.greaterThanMax": "Min. value cannot be greater than max. value",
    "dataType.number.max.label": "Max.",
    "dataType.number.max.tooltip":"Upper bound for generated numbers",
    "dataType.number.max.errorMessage.empty": "Max. value cannot be empty",
    "dataType.number.max.errorMessage.lessThanMin": "Max. value cannot be less than min. value",

    // dateTime
    "dataType.dateTime": "Date time",

    // boolean
    "dataType.boolean": "Boolean",
    "dataType.boolean.true.label": "Prob of True",
    "dataType.boolean.true.tooltip": "Probability of generating true value",
    "dataType.boolean.true.errorMessage.empty": "Prob of True cannot be empty",
    "dataType.boolean.format.label": "Format",

    // full name
    "dataType.fullName": "Full name",
    "dataType.fullName.sex.label": "Sex",
    "dataType.fullName.sex.selectOptions.all": "Male, Female",
    "dataType.fullName.sex.selectOptions.male": "Male",
    "dataType.fullName.sex.selectOptions.female": "Female",
    "dataType.fullName.firstName.label": "First name",
    "dataType.fullName.lastName.label": "Last name",

    // account number
    "dataType.accountNumber": "Account number",

    // -------------------------------------------------------------------------------------------------------------
    // pages

    // nav bar
    "nav.item.home": "Home",
    "nav.item.workspace": "Workspace",
    "nav.item.about": "About",
    "nav.colorModeSwitchButton.switchToDarkMode.text": "Switch to dark mode",
    "nav.colorModeSwitchButton.switchToLightMode.text": "Switch to light mode",
    "nav.languageSwitchButton.tooltip": "Language",
    "nav.languageSwitchModal.title": "Select language",
    "nav.languageSwitchModal.footer.chatGPT.text": "Translations generated by ChatGPT",

    // workspace
    "toolbar.numOfRowInput.suffix": "Rows",
    "toolbar.generateButton.text": "Generate",
    "toolbar.panelsOrientationButton.tooltip.switchToColumn": "Switch panels to column",
    "toolbar.panelsOrientationButton.tooltip.switchToRow": "Switch panels to row",
    "toolbar.emptyPageButton.tooltip": "Empty workplace",
    "toolbar.emptyPageButton.confirmation.title": "Empty workplace",
    "toolbar.emptyPageButton.confirmation.text": "Are you sure you want to empty the workplace? All the workplace configurations you have set up will be lost.",
    "toolbar.exportSchemaButton.tooltip": "Export schema",
    "toolbar.importSchemaButton.tooltip": "Import schema",
    "preview.setting.regenerateButton.tooltip": "Regenerate",
    "preview.setting.lineNumberSwitch.tooltip.show": "Show line number",
    "preview.setting.lineNumberSwitch.tooltip.hide": "Hide line number",
    "preview.setting.lineWarpSwitch.tooltip.enable": "Enable line wrap",
    "preview.setting.lineWarpSwitch.tooltip.disable": "Disable line wrap",
    "preview.setting.copyToClipboard.tooltip": "Copy to clipboard",
    "preview.setting.copyToClipboard.notification.success": "Success",
    "preview.setting.copyToClipboard.notification.content": "Copied to the clipboard.",
    "preview.setting.rawView.text": "Raw",
    "preview.setting.tableView.text": "Table",
    "dataFields.list.addNewFieldButton.text": "Add field",
    "dataFields.input.fieldName.label": "Field name",
    "dataFields.input.fieldName.errorMessage.empty": "Field name cannot be empty",
    "dataFields.input.type.label": "Type",
    "dataFields.input.type.placeholder": "Select type",
    "dataFields.input.emptyRate.label": "Empty %",
    "dataFields.input.emptyRate.tooltip": "Probability of generating empty value",
    "dataFields.input.emptyRate.errorMessage.empty": "Empty rate cannot be empty",
    "dataFields.input.options.label": "Options",
    "dataFields.type.modal.title": "Data types",
    "dataFields.type.modal.search.placeholder": "Search data type...",

    // error pages
    "error.404.description": "Page does not exist",
    "error.404.button.text": "Home page",
    "error.general.description": "Oops! An error has occurred!",
    "error.general.button.text": "Home page",
}