export const en = {

    // -------------------------------------------------------------------------------------------------------------
    // export

    // export category
    "export.category.fileTypes": "General file types",
    "export.category.programmingLanguages": "Programming languages",

    // export format modal
    "export.configurator.modal.title": "Export Format",
    "export.configurator.modal.closeButton.text": "Close",
    "export.configurator.config.label": "Configurations",
    "export.configurator.config.empty": "Configuration of this export format is currently not available.",

    // csv
    "export.configurator.csv.delimiter": "Delimiter",
    "export.configurator.csv.includeHeader": "Include header",
    "export.configurator.csv.endLineChar": "End of line characters",

    // -------------------------------------------------------------------------------------------------------------
    // data types

    // data type category
    "dataType.category.all": "All",
    "dataType.category.basic": "Basic",
    "dataType.category.person": "Person",
    "dataType.category.commerce": "Commerce",

    // number
    "dataType.number": "Number",

    // dateTime
    "dataType.dateTime": "Date time",

    // boolean
    "dataType.boolean": "Boolean",

    // person name
    "dataType.personName": "Person name",

    // account mi,ner
    "dataType.accountNumber": "Account number",

    // -------------------------------------------------------------------------------------------------------------
    // pages

    // nav bar
    "nav.item.home": "Home",
    "nav.item.workspace": "Workspace",
    "nav.item.about": "About",
    "nav.colorModeSwitchButton.switchToDarkMode.text": "Switch to dark mode",
    "nav.colorModeSwitchButton.switchToLightMode.text": "Switch to light mode",
    "nav.languageSwitchButton.tooltip": "Language",
    "nav.languageSwitchModal.title": "Select language",
    "nav.languageSwitchModal.footer.chatGPT.text": "Translations generated by ChatGPT",

    // workspace
    "toolbar.numOfRowInput.suffix": "Rows",
    "toolbar.generateButton.text": "Generate",
    "toolbar.panelsOrientationButton.tooltip.switchToColumn": "Switch panels to column",
    "toolbar.panelsOrientationButton.tooltip.switchToRow": "Switch panels to row",
    "toolbar.emptyPageButton.tooltip": "Empty workplace",
    "toolbar.emptyPageButton.confirmation.title": "Empty workplace",
    "toolbar.emptyPageButton.confirmation.text": "Are you sure you want to empty the workplace? All the workplace configurations you have set up will be lost.",
    "toolbar.exportSchemaButton.tooltip": "Export schema",
    "toolbar.importSchemaButton.tooltip": "Import schema",
    "preview.setting.regenerateButton.tooltip": "Regenerate",
    "preview.setting.lineNumberSwitch.tooltip.show": "Show line number",
    "preview.setting.lineNumberSwitch.tooltip.hide": "Hide line number",
    "preview.setting.lineWarpSwitch.tooltip.enable": "Enable line wrap",
    "preview.setting.lineWarpSwitch.tooltip.disable": "Disable line wrap",
    "preview.setting.copyToClipboard.tooltip": "Copy to clipboard",
    "preview.setting.copyToClipboard.notification.success": "Success",
    "preview.setting.copyToClipboard.notification.content": "The content has been copied to the clipboard.",
    "preview.setting.rawView.text": "Raw",
    "preview.setting.tableView.text": "Table",
    "dataFields.list.addNewFieldButton.text": "Add field",
    "dataFields.input.fieldName.label": "Field name",
    "dataFields.input.type.label": "Type",
    "dataFields.input.type.placeholder": "Select type",
    "dataFields.input.emptyRate.label": "Empty %",
    "dataFields.type.modal.title": "Data types",
    "dataFields.type.modal.search.placeholder": "Search data type...",

    // error pages
    "error.404.description": "Page does not exist",
    "error.404.button.text": "Home page",
    "error.general.description": "Oops! An error has occurred!",
    "error.general.button.text": "Home page",
}